name: ngrx workflow

on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
    
        - name: Install dependency
          run: |
              npm install --f

        - name: Clone ngrx2 Repository
          run: |
            git clone https://x-access-token:${{ secrets.TOKEN_NGRX }}@github.com/Jinal207/ngrx2.git ngrxNew
            cd ngrxNew
            git checkout feature/demo

        - name: Check if repository is cloned
          run: |
            if [ -d "ngrxNew" ]; then
              echo "Repository cloned successfully."
              cd ngrxNew
              git status
            else
              echo "Cloning failed."
              exit 1
            fi

        - name: Check contents of src/app
          run: |
            cd ngrxNew/src/app
            echo "Current directory structure:"
            ls -R .

        - name: Remove old files in src/app
          run: |
              echo "Current directory before removal:"
              pwd
              ls -R ngrxNew/src/app
              rm -rf ngrxNew/src/app/*

        - name: Contents of src after remove
          run: |
            cd ngrxNew/src/app
            echo "Contents of extension/src after remove:"
            ls -R .

        - name: Copy Build to ngrx Repository
          run: |
            cp -R src/app ngrxNew/src/app 
            cd ngrxNew

        - name: Contents of src after copy
          run: |
            cd ngrxNew/src/app
            echo "Contents of extension/src before copy:"
            ls -R .

        - name: Go back to the original repo
          run: |
            cd ..
            echo "Back to the original repository"
            ls -R .




